language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install tensorflow
  - pip install pytest
script:
  - source pythonpath.sh
  - pytest -v --doctest-modules python/seqtrack/
