language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install nose
script:
  - source pythonpath.sh
  - nosetests -v --with-doctest --nologcapture seqtrack
